### ISSUE TITLE
Plugin doesn't work for Sublime 3114, please check pfronczak's last reply

### ISSUE THREAD

**Issue by eugenevabishchevich** [xjsender/haoide#112]
Hey!

I have updated sublime to 3114 and plugin doesn't work. Could you help?

**Comment by xjsender** [comment]
@eugenevabishchevich , I am also experienced the same problem, as you see, in the [sublime home page](https://www.sublimetext.com/3), the latest sublime version is also rollback, you can see the [cached page](https://webcache.googleusercontent.com/search?q=cache:9RZwhktSLZUJ:https://www.sublimetext.com/3+&cd=1&hl=en&ct=clnk&gl=hk) by google.

I think, there are some bugs in the new version, which may be caused by update of ``buildin python lib``, please downgrade your sublime to ``3103``, after that, it will ok.

Thanks.

**Comment by eugenevabishchevich** [comment]
Ok, thanks!

**Comment by reyesml** [comment]
Here's a portable version of 3103 for windows x64

https://download.sublimetext.com/Sublime%20Text%20Build%203103%20x64.zip

**Comment by SunLangzi** [comment]
mac上也一样，sublime 升级后，switch project 按钮就是灰色的。windows的也一样

**Comment by xjsender** [comment]
@SunLangzi , ge men, please downgrade your sublime. 

BTW, you can jian ru QQ group (190704724) for online support if you want.

**Comment by SunLangzi** [comment]
您要加入的群满员！ 😓

**Comment by alker7** [comment]
I downgraded to 3103 and it works again. For MacOS click here
https://download.sublimetext.com/Sublime%20Text%20Build%203103.dmg

**Comment by gmwamsoyo** [comment]
Can anybody share 3103 downgrade for Windows?

**Comment by eugenevabishchevich** [comment]
You can try to change version of sublime in download link. It works for mac.

**Comment by gmwamsoyo** [comment]
I got HaoIDE active again on ST3 for Windows by downloading build 3103 from
https://download.sublimetext.com/Sublime%20Text%20Build%203103%20x64%20Setup.exe

**Comment by pfronczak** [comment]
Hi,
While downgrading Sublime is a valid workaround are there any plans to actually fix this compatibility issue? It looks like the update 3114 is going to stay (https://www.sublimetext.com/3).

**Comment by xjsender** [comment]
@pfronczak , sorry, I just checked it, ``sublime 3114`` is not available to download.

**Comment by xjsender** [comment]
@pfronczak , actually, I can't fix this problem, you should request help from ``package control``.

If you really want to use ``haoide`` in sublime 3114, you can manually install this plugin.

----
**How to manually install this plugin**
* Download Zip
* Extract your file as below screenshot

![image](https://cloud.githubusercontent.com/assets/1450977/15319382/27f3b3de-1c5d-11e6-8da5-4eafa74e5382.png)

**Comment by pfronczak** [comment]
I've done some digging and got to the bottom of this issue. Here's what's happening:
* one of the files in `haoide` package (`salesforce/lib/dateutil/parser.py`) is not utf-8 encoded and when Sublime reads the contents of zipped packages it assumes that all files inside are utf-8 encoded
* previously that wasn't a big issue because Sublime was just skipping over such files and the package was loaded successfully
* in build 3114 Sublime introduced a bug in the error handling of non utf-8 encoded files which caused the whole process of loading the plugins to crash if it encountered one non utf-8 encoded file.

The good news is that this has been already reported and Sublime devs promised to fix it (https://forum.sublimetext.com/t/package-control-not-available/20120/4)

So, as @xjsender mentioned - nothing to fix on `haoide` side, but in the meantime, if anyone wants to use `haoide` with Sublime build 3114 you can either extract the plugin (as mentioned above) or if you want the `haoide` to stay managed by Package Control you can easily fix the Sublime bug yourself:
* In your main Sublime Text folder there's a `sublime_plugin.py` file. All you have to do is change the line 728 from:
```python
print(f, "in", zippath, "is not utf-8 encoded, unable to load plugin")
```
to
```python
print(f, "in", self.zippath, "is not utf-8 encoded, unable to load plugin")
```

**Comment by xjsender** [comment]
@pfronczak , thanks for your information about this issue, It's a obvious bug of the sublime.

I just did it as your mentioned and it worked.

Thanks.
