### ISSUE TITLE
idea: auto-refresh list with logs from server?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [xjsender/haoide#121]
After some action with Salesforce I need to `fetch self` and wait few seconds - will be better if every five seconds list with logs synced.

**Comment by xjsender** [comment]
@vitaly-zdanevich , because ``haoide`` is written by python which doesn't support ``Bayeux Protocol`` for ``Streaming API``, if we try to pull debug logs with backend thread, it is a waste for ``API consuming``.

Editors based on Nodejs like Atom, Brackets and Visual Code can support ``Bayeux Protocol``, however, I have no planning for this.

**Comment by vitaly-zdanevich** [comment]
ok, but your link is 404

**Comment by xjsender** [comment]
It is ok now, sorry.
