### ISSUE TITLE
Status bar not updating upon project switch

### ISSUE THREAD

**Issue by DrByrnes** [xjsender/haoide#39]
It doesn't appear that the status bar is updating with the active project when the 'Switch Project' command is executed.

To replicate:

 - Open Sublime
 - Note that the status bar properly indicates the current active HaoIDE project.
 - HaoIDE --> Switch Project --> Any other project that isn't currently active
 - Note that it (probably) says '... project login succeeded', (temporarily) however the status bar text still tells me Default Project => [Prior Project Name] (v33.0).

**Comment by xjsender** [comment]
@DrByrnes , it is known issue, in your case, there is no active view or open file in sublime, is it right?

The root cause is, status bar message is a attribute of view, however, if you didn't open any file, it means there is no active view in sublime, so plugin will not set the status bar message for view.

I can create a empty view when you switch project and there is no any other active view, and then set the staus var message for the empty view, is it ok?

**Comment by DrByrnes** [comment]
I didn't realize this was known.  I figured it was just a timing thing.  If this makes sense to solve this way, it sounds good to me.  It's obviously very, very minor so feel free to ignore it - I just noticed it and thought I'd report it.

**Comment by xjsender** [comment]
@DrByrnes , it is known issue but just known by me. I will fix it as I said in the previous comment.

**Comment by xjsender** [comment]
I thought the solution is not good enough, so I never did it.
