### ISSUE TITLE
Feature Request: Allow users to specify metadata polling frequency

### ISSUE THREAD

**Issue by reyesml** [xjsender/haoide#44]
HaoIDE checks the status of the "update project" request every second.  Each poll for the status counts against salesforce's API usage limits.  We should allow the user to specify the polling interval to reduce API usage when needed.

**Comment by xjsender** [comment]
@reyesml , you are right, I just copied this solution from Salesforce Ant, allowing user to specifying the polling interval is a good idea to reduce API usage.

In order to keep consist with other settings, can you please change your setting name with the same convention of other settings, after that, I will merge your pull request.

Thanks for your help on this plugin.
