### ISSUE TITLE
Ability to use eclipse project as sublime project

### ISSUE THREAD

**Issue by ashishcloud** [xjsender/haoide#75]
Hi,

Is there any way by which we can use existing eclipse project as a sublime project.

Actually we are working in a team and we have a eclipse project in git repository.

We can use this project in eclipse but cant use this in sublime as a haoide projecct.

**Comment by xjsender** [comment]
@ashishcloud , this enhancement is not valid due to many problem, such as,  
* project name is not compatible with the rule of haoide
* In order to speed up development, haoide maintain the attributes of every component in the local cache but eclipse not.

Actually, there are lots of manual change needed to finish before import eclipse project as haoide project, I will roll back the enhancement today, sorry for the problem.
